package com.biubiu.miku.util.video.action.filter;

public enum FilterThemeType {
  ORIGIN, EINSTEIN, ISABELLA, KYOTO, LOMO, CITY, VELVET, PINK, RAIN, MONET, FUJI, HITCHCOCK, GARDEN,
  OZ, FIREFLY, HUGO, PARIS, LATTE, SUNLIGHT, FROST, WAVES, CAPPUCCINO, SAKURA,CHAPLIN
}
