package com.biubiu.miku.util.video.action.subtitle;

public enum SubtitleType {
  CARTOON_WHITE, CARTOON_EN,CARTOON_BLACK, CARTOON_JP,
  CLASSIC_WHITE, CLASSIC_EN, CLASSIC_BLACK, CLASSIC_JP,
  LOVE_NOTE_YELLOW,LOVE_NOTE_LIGHT_YELLOW,LOVE_NOTE_WHITE,
  OFFICE_STORY_YELLOW,OFFICE_STORY_RED,OFFICE_STORY_BLUE,
  JP_STYLE_ORIGIN, JP_STYLE_BLACK, JP_STYLE_BLUE,
  JP_STYLE_ORANGE, JP_STYLE_YELLOW
}
