package com.biubiu.miku.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table POST_VIDEO.
 */
public class PostVideo {

    private Long id;
    private String key;
    private String originVideoPath;
    private String cropVideoPath;
    private String videoMetaData;
    private int actionLocationTaskPosition;
    private Float videoRatioWH;
    private Integer sampleSize;
    private Long timestamp;
    private String recordActionLocationTasks;
    private Integer state;

    public PostVideo() {
    }

    public PostVideo(Long id) {
        this.id = id;
    }

    public PostVideo(Long id, String key, String originVideoPath, String cropVideoPath, String videoMetaData, int actionLocationTaskPosition, Float videoRatioWH, Integer sampleSize, Long timestamp, String recordActionLocationTasks, Integer state) {
        this.id = id;
        this.key = key;
        this.originVideoPath = originVideoPath;
        this.cropVideoPath = cropVideoPath;
        this.videoMetaData = videoMetaData;
        this.actionLocationTaskPosition = actionLocationTaskPosition;
        this.videoRatioWH = videoRatioWH;
        this.sampleSize = sampleSize;
        this.timestamp = timestamp;
        this.recordActionLocationTasks = recordActionLocationTasks;
        this.state = state;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getOriginVideoPath() {
        return originVideoPath;
    }

    public void setOriginVideoPath(String originVideoPath) {
        this.originVideoPath = originVideoPath;
    }

    public String getCropVideoPath() {
        return cropVideoPath;
    }

    public void setCropVideoPath(String cropVideoPath) {
        this.cropVideoPath = cropVideoPath;
    }

    public String getVideoMetaData() {
        return videoMetaData;
    }

    public void setVideoMetaData(String videoMetaData) {
        this.videoMetaData = videoMetaData;
    }

    public int getActionLocationTaskPosition() {
        return actionLocationTaskPosition;
    }

    public void setActionLocationTaskPosition(int actionLocationTaskPosition) {
        this.actionLocationTaskPosition = actionLocationTaskPosition;
    }

    public Float getVideoRatioWH() {
        return videoRatioWH;
    }

    public void setVideoRatioWH(Float videoRatioWH) {
        this.videoRatioWH = videoRatioWH;
    }

    public Integer getSampleSize() {
        return sampleSize;
    }

    public void setSampleSize(Integer sampleSize) {
        this.sampleSize = sampleSize;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public String getRecordActionLocationTasks() {
        return recordActionLocationTasks;
    }

    public void setRecordActionLocationTasks(String recordActionLocationTasks) {
        this.recordActionLocationTasks = recordActionLocationTasks;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public enum State{
        FAILED, SAVED
    }
}
